name: Daily Digest

on:
  schedule:
    - cron: "0 1 * * *"   # 01:00 UTC = 08:00 VN
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      # Kiểm tra secrets trước khi chạy
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.SMTP_HOST }}" ] || [ -z "${{ secrets.SMTP_USER }}" ] || [ -z "${{ secrets.SMTP_PASS }}" ] || [ -z "${{ secrets.EMAIL_TO }}" ] || [ -z "${{ secrets.DEEPSEEK_API_KEY }}" ]; then
            echo "❌ Missing required secrets. Please configure:"
            echo "- SMTP_HOST"
            echo "- SMTP_USER" 
            echo "- SMTP_PASS"
            echo "- EMAIL_TO"
            echo "- DEEPSEEK_API_KEY"
            exit 1
          fi
          echo "✅ All secrets configured"
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-deps html2text  # Tránh conflict
      
      - name: Run news digest
        run: python clean_news_digest.py
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
