name: Daily Digest

on:
  schedule:
    - cron: "40 16 * * *"   # 16:40 UTC = 23:40 VN
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: python -m nltk.downloader punkt

      - name: Run digest
        run: python news_digest.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:  ${{ secrets.EMAIL_TO }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
